### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by scottaohara** [ericwbailey/accessible-html-content-patterns#5]
https://github.com/ericwbailey/accessible-html-content-patterns/blob/6f0c4b077228d0043e873b1aca8d2fdb9d8bc959/partials/section.embedded.hbs#L9

Exmaple => Example
:)

**Comment by ericwbailey** [comment]
Closed via https://github.com/ericwbailey/accessible-html-content-patterns/commit/c618739de874aefd16f023b7420894150b24daca, you magnificent bastard.
