### ISSUE TITLE
Live GH-Pages is down

### ISSUE THREAD

**Issue by aceyoung9** [ericwbailey/accessible-html-content-patterns#7]
# Live GitHub Pages is down.

## Expected behavior
a build at http://ericwbailey.github.io/accessible-html-content-patterns/ (what the link is from the repo sidebar)

## Actual behavior

a 404 page, and not even one with a unicorn.

![Screenshot of a 404 error screen](https://user-images.githubusercontent.com/2482343/92957991-75812d00-f437-11ea-987e-25fad11acb35.png)

## Steps to reproduce behavior
http://ericwbailey.github.io/accessible-html-content-patterns/

Might be something caused by a branch rename? Recheck the repo settings?

Thanks!

**Comment by ericwbailey** [comment]
Oop! I forgot to update GitHub pages after updating the main branch name to `main`. Should be fixed now, can I trouble you to confirm?

**Comment by aceyoung9** [comment]
🎉  I see a build! Thanks!
